version: "3"

tasks:
  format:
    cmds:
      - deno fmt .
      - gofmt -w .
  lint: golangci-lint run --fix --timeout "10m"
  test: go test -v -race ./...
  default:
    cmds:
      - task: format
      - task: lint
      - task: test
